// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XMEN.Infrastructure.Configurations.Data;

namespace XMEN.Infrastructure.Migrations
{
    [DbContext(typeof(MutantContext))]
    partial class MutantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("XMEN.Core.Entities.VerifiedDNAHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DNA")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<bool>("IsMutant")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedUTC")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("VerifiedDNAHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
